# Generated by Django 5.0.9 on 2025-10-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_parkinglocation_reservation_delete_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglocation",
            name="total_spots",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
